### Create conference
POST http://localhost:8000/conference
Content-Type: application/json
Authorization: Basic am9obi5kb2VAZ21haWwuY29tOnF3ZXJ0eQ==

{
    "title": "Ma nouvelle conference",
    "seats": 100,
    "startDate": "2025-04-21T10:00:00.000Z",
    "endDate": "2025-04-21T12:00:00.000Z"
}