### Create conference
POST http://localhost:8000/conferences
Content-Type: application/json

{
    "title": "Ma nouvelle conference",
    "seats": 50,
    "startDate": "2025-05-25T10:00:00.000Z",
    "endDate": "2025-05-25T12:00:00.000Z"
}